apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: public.ecr.aws/nginx/nginx:1.26
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
